url: "https://tfscmdlets.dev"
permalink: pretty
exclude: ["vendor", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "TfsCmdlets on GitHub":
    - "https://github.com/igoravl/tfscmdlets/"
  "Downloads":
    - "https://github.com/igoravl/tfscmdlets/releases/"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2014-2021 Igor Abade V. Leite. Distributed by an <a href=\"https://github.com/igoravl/tfscmdlets/tree/master/LICENSE.md\">MIT license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

plugins:
  - jekyll-seo-tag
  - jekyll-regex-replace

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

defaults:
  -
    scope:
      path: "docs/cmdlets"
    values:
      layout: "cmdlet"
      nav_exclude: true

build_info: TfsCmdlets v2.0.0-PullRequest0130.77, released 2021-04-11

build_info: TfsCmdlets v2.0.0-PullRequest0130.78, released 2021-04-11

build_info: TfsCmdlets v2.0.0-PullRequest0130.79, released 2021-04-12

build_info: TfsCmdlets v2.0.0-PullRequest0130.80, released 2021-04-12

build_info: TfsCmdlets v2.0.0, released 2021-08-02

build_info: TfsCmdlets v2.0.1+2474.3, released 2021-08-02

build_info: TfsCmdlets v2.1.0+2485.8, released 2021-08-13

build_info: TfsCmdlets v2.1.1+2511.1, released 2021-09-08

build_info: TfsCmdlets v2.1.2+2513.2, released 2021-09-10

